### ISSUE TITLE
Concerns regarding using MSMC-IM with unequal haplotype counts between populations

### ISSUE THREAD

**Issue by Luker121** [wangke16/MSMC-IM#11]
I am currently using MSMC-IM for inferring migration rates between two populations, and I have encountered a situation where one population has a significantly larger number of haplotypes than the other population. I understand that MSMC-IM fits a continuous Isolation-Migration (IM) model with time-dependent population sizes and migration rates based on coalescence rates estimated from MSMC or MSMC2.

However, I am concerned about potential biases that may arise due to the unequal sample sizes. Therefore, I would like to ask, whether you have addressed this issue already somewhere? Or provided any recommendations for using MSMC-IM (MSMC2) in such scenarios. Or would you always recommend using an equal number of haplotypes for both populations (when using two populations)

I am looking forward to hear back from you.

**Comment by stschiff** [comment]
See https://github.com/stschiff/msmc-tools/issues/53
