### ISSUE TITLE
Application to non-human organisms

### ISSUE THREAD

**Issue by stsmall** [wangke16/MSMC-IM#2]
Hi Ke,
I am using your program to look at divergence/migration for non-human organisms. Since your program was specifically tuned for humans, what all should I change?
-I changed Line 11 in MSMC_IM_funcs.py to reflect the mutation rate in my organism; mu=2.8e-09 
-I used an estimate of theta from getStats.d (msmc-tools) to calculate the initial Ne values for -N1 9e5 and -N2 9e5.
The results look promising compared to other methods we have used. Just wanted to verify with you that there wasnt anything that I was overlooking.
thanks,
@stsmall

**Comment by wangke16** [comment]
hi scott
I think the mutation rate is the most critical thing you need to change for a different organism. That's exactly where it should be changed. Thanks for bring this up.
The initial Ne values are less important actually. But if you begin with more reasonable initial values, I think it would save time for running the program. 
In the case of human, we ignore m(t) estimates after the time when the probability M(t) reaches 0.999. Same rule applies to any other organism as well. hope this helps.
best
Ke
