### ISSUE TITLE
TypeError: stem() got an unexpected keyword argument 'c'

### ISSUE THREAD

**Issue by biozzq** [wangke16/MSMC-IM#6]
Dear @wangke16 

Thank you for your excellent tools. I want to use it to help me better interpret the results of MSMC2, however it failed when using following command. Please note that the command also generates two files: `SEA-Wild-SEA-Dom.b1_1e-08.b2_1e-06.MSMC_IM.estimates.txt`, `SEA-Wild-SEA-Dom.b1_1e-08.b2_1e-06.MSMC_IM.fittingdetails.txt`.

`python /MSMC-IM/MSMC_IM.py -mu 2.5e-8 -p 1*2+20*1+1*2+1*3 -o /03.MSMC_IM/SEA-Wild-SEA-Dom --printfittingdetails --plotfittingdetails --xlog /02.MSMC/SEA-Wild-SEA-Dom.CCR`
```
##############################################################################
/MSMC-IM/MSMC_IM.py:164: UserWarning: Attempted to set non-positive left xlim on a log-scaled axis.
Invalid limit will be ignored.
  plt.xlim(0, 2e5)
/MSMC-IM/MSMC_IM.py:170: UserWarning: Attempted to set non-positive left xlim on a log-scaled axis.
Invalid limit will be ignored.
  plt.xlim(0, 2e5)
/MSMC-IM/MSMC_IM.py:182: UserWarning: Attempted to set non-positive left xlim on a log-scaled axis.
Invalid limit will be ignored.
  plt.xlim(0, 2e5)
Traceback (most recent call last):
  File "/MSMC-IM/MSMC_IM.py", line 191, in <module>
    plt.stem(xVec, yVec, linefmt=':', c='orange')
TypeError: stem() got an unexpected keyword argument 'c'
```

Sincerely,
Zheng zhuqing

**Comment by stschiff** [comment]
OK, I think in order for @wangke16 to reproduce this you should send her your input data...

**Comment by biozzq** [comment]
Hi @wangke16 

I attached the CCR file here, and the command I used is as follows;

`python ./MSMC-IM/MSMC_IM.py -mu 2.5e-8 -p 1*2+20*1+1*2+1*3 -o ./out/SEA-Wild-SEA-Dom --printfittingdetails --plotfittingdetails --xlog SEA-Wild-SEA-Dom.CCR.txt`

[SEA-Wild-SEA-Dom.CCR.txt](https://github.com/wangke16/MSMC-IM/files/6694266/SEA-Wild-SEA-Dom.CCR.txt)

Best regards,

**Comment by wangke16** [comment]
Hi Zhuqing,

it’s a python plotting issue. I have fixed it. Please try again. TypeError should be gone now and you will get your fitting details in the output PDF file.

Best.

**Comment by biozzq** [comment]
Hi @wangke16 

Thank you, it is ok now.

Best.
