### ISSUE TITLE
R script to plot MSMC-IM results

### ISSUE THREAD

**Issue by DuttaAnik** [wangke16/MSMC-IM#9]
Dear Wang,

Is there any custom R-script to plot the migration rate manually rather than the automatic generation by using the options in `MSMC-IM.py`? 

If there is any formula that I need to scale the variable to the plot, then can you please let me know?
thank you.

Regards
Anik

**Comment by stschiff** [comment]
I'm pinging @wangke16

**Comment by DuttaAnik** [comment]
Dear Dr. Schiffels,

Have you received any response from @wangke16?

**Comment by wangke16** [comment]
Hi,  you could do ggplot in R (see pseudo code bellow). if you would like to visualise migration rate in years, then you need scale the time to years by multiplying the generation time (assuming 29 years) before plotting.

`ggplot(msmcim_m, aes(x = t, y = m)) + geom_ribbon(aes(ymin=0, ymax = m)) +
    scale_x_continuous(limits = c(1e3,2e7), breaks=c(1e3,1e4,4e4,8e4,2e5,6e5,1e6,4e6,8e6), trans='log10') + 
    theme_bw() + labs(title="migration rate (view backward in time)", x = "years(log)")  `

**Comment by DuttaAnik** [comment]
Hi, thank you very much for the code. I already figured it out. I thought it has some kind of formula similar to when plotting relative cross-coalescent from MSMC2. Thank you very much, anyways.

Regards
Anik
